# Generated by Django 5.1.1 on 2024-10-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_and_prof_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='price_fr',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='title_fr',
        ),
    ]
